services:
  - type: web
    name: insurance-docs
    env: docker
    plan: free
    branch: main
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://atharvashinde811_db_user:jUfWnUzeVGpmiqQg@cluster1.hygoiiw.mongodb.net/insurance_db?appName=Cluster1
